### ISSUE TITLE
1등 솔루션 예제 코드를 돌리다가 아래와 같은 CUDA error: device-side assert triggered 오류가 나 해결 방법이 있나 해서 글 남깁니다. 

### ISSUE THREAD

**Issue by tae-min-lee** [lime-robot/categories-prediction#1]
ubuntu@nipa2021-35521:~/taemin/categories-prediction/code$ python train.py --fold 0
2021-11-22 11:04:25.561968: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Device: cuda
Current cuda device: 0
Count of using GPUs: 1
{'__module__': '__main__', 'learning_rate': 0.0003, 'batch_size': 1024, 'num_workers': 4, 'print_freq': 100, 'start_epoch': 0, 'num_train_epochs': 3, 'warmup_steps': 100, 'max_grad_norm': 10, 'weight_decay': 0.01, 'dropout': 0.2, 'hidden_size': 512, 'intermediate_size': 256, 'nlayers': 2, 'nheads': 8, 'seq_len': 64, 'n_b_cls': 58, 'n_m_cls': 553, 'n_s_cls': 3191, 'n_d_cls': 405, 'vocab_size': 32000, 'img_feat_size': 2048, 'type_vocab_size': 30, 'csv_path': '/home/ubuntu/taemin/categories-prediction/input/processed/train.csv', 'h5_path': '/home/ubuntu/taemin/categories-prediction/input/processed/train_img_feat.h5', '__dict__': <attribute '__dict__' of 'CFG' objects>, '__weakref__': <attribute '__weakref__' of 'CFG' objects>, '__doc__': None, 'seed': 7}
loading ...
loading ... done
parameters:  24637551
num_train_optimization_steps 19065
use WarmupLinearSchedule ...
initial learning rate:0.0
/opt/conda/conda-bld/pytorch_1634272115665/work/aten/src/ATen/native/cuda/Loss.cu:455: nll_loss_backward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [11,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1634272115665/work/aten/src/ATen/native/cuda/Loss.cu:455: nll_loss_backward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [15,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "train.py", line 514, in <module>
    main()
  File "train.py", line 233, in main
    train_res = train(train_loader, model, optimizer, epoch, scheduler)
  File "train.py", line 316, in train
    loss.backward()
  File "/home/ubuntu/anaconda3/envs/transformers/lib/python3.6/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/ubuntu/anaconda3/envs/transformers/lib/python3.6/site-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: CUDA error: device-side assert triggered

github에 있는 code에서 따로 수정한 부분은 없었습니다.

**Comment by tae-min-lee** [comment]
(base_1) C:\Users\taemi\workspace\categories-prediction\code>python train.py --fold 0
{'__module__': '__main__', 'learning_rate': 0.0003, 'batch_size': 512, 'num_workers': 4, 'print_freq': 100, 'start_epoch': 0, 
'num_train_epochs': 10, 'warmup_steps': 100, 'max_grad_norm': 10, 'weight_decay': 0.01, 'dropout': 0.2, 'hidden_size': 512, 'intermediate_size': 256, 'nlayers': 2, 'nheads': 8, 'seq_len': 64, 'n_b_cls': 68, 'n_m_cls': 563, 'n_s_cls': 3201, 'n_d_cls': 415, 'vocab_size': 32000, 'img_feat_size': 2048, 'type_vocab_size': 30, 'csv_path': 'C:\\Users\\taemi\\workspace\\categories-prediction\\input\\processed\\train.csv', 'h5_path': 'C:\\Users\\taemi\\workspace\\categories-prediction\\input\\processed\\train_img_feat.h5', '__dict__': <attribute '__dict__' of 'CFG' objects>, '__weakref__': <attribute '__weakref__' of 'CFG' objects>, '__doc__': None, 'seed': 7}
loading ...
loading ... done
parameters:  24658071
num_train_optimization_steps 93750
use WarmupLinearSchedule ...
initial learning rate:0.0
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:455: block: [0,0,0], thread: [7,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:455: block: [0,0,0], thread: [11,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:455: block: [0,0,0], thread: [27,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "train.py", line 493, in <module>
    main()
  File "train.py", line 215, in main
    train_res = train(train_loader, model, optimizer, epoch, scheduler)
  File "train.py", line 296, in train
    loss.backward()
  File "C:\Users\taemi\anaconda3\envs\base_1\lib\site-packages\torch\_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\taemi\anaconda3\envs\base_1\lib\site-packages\torch\autograd\__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA error: device-side assert triggered

네 이렇게 같은 오류가 나옵니다.

**Comment by tae-min-lee** [comment]
vscode에서 진행하였습니다.

**Comment by tae-min-lee** [comment]
window10
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.relgpu_drvr455TC455_06.29069683_0
conda 4.10.1
Python 3.8.11
pytorch 1.10.0+cu113 에서 돌렸었습니다.

**Comment by tae-min-lee** [comment]
그리고 requirements에 남겨두신 버전으로 돌리면 아래와 같이 다른 오류가 발생했습니다.
File "train.py", line 8, in <module>
    import cate_model
  File "C:\Users\taemi\workspace\categories-prediction\code\cate_model.py", line 4, in <module>
    from transformers import BertConfig, BertModel
  File "C:\Users\taemi\anaconda3\lib\site-packages\transformers\__init__.py", line 626, in <module>
    from .trainer import Trainer
  File "C:\Users\taemi\anaconda3\lib\site-packages\transformers\trainer.py", line 69, in <module>
    from .trainer_pt_utils import (
  File "C:\Users\taemi\anaconda3\lib\site-packages\transformers\trainer_pt_utils.py", line 40, in <module>
    from torch.optim.lr_scheduler import SAVE_STATE_WARNING
ImportError: cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler' (C:\Users\taemi\anaconda3\lib\site-packages\torch\optim\lr_scheduler.py)
